### ISSUE TITLE
handle csv.Error in _parse_batch_result from NUL

### ISSUE THREAD

**Issue by themikesmith** [fitnr/censusgeocode#14]
Occasionally the data returned from the API (unclear whether it's an artifact of a connection error, etc.; I am currently investigating) contains NULL bytes. (This is not a consequence of NULL being in the input data.)

This causes the following error, which I propose this library should handle if it doesn't impact the data being returned (currently investigating, will report back)

```
Traceback (most recent call last):
  File "batch_geocode.py", line 121, in <module>
    result = censusgeocode.addressbatch(data=current_batch, **cg_kwargs)
  File "<...path to my venv...>/lib/python3.7/site-packages/censusgeocode/censusgeocode.py", line 213, in addressbatch
    return self._post_batch(data=data, **kwargs)
  File "<...path to my venv...>/lib/python3.7/site-packages/censusgeocode/censusgeocode.py", line 187, in _post_batch
    return self._parse_batch_result(r.text, returntype)
  File "<...path to my venv...>/lib/python3.7/site-packages/censusgeocode/censusgeocode.py", line 158, in _parse_batch_result
    return [parse(row) for row in reader]
  File "<...path to my venv...>/lib/python3.7/site-packages/censusgeocode/censusgeocode.py", line 158, in <listcomp>
    return [parse(row) for row in reader]
  File "<...path to my venv...>/lib/python3.7/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte
```
I am currently testing whether adding the following on line 157 helps:
`reader = csv.DictReader(f, fieldnames=fieldnames**, quoting=csv.QUOTE_ALL**)`

Will report back.

**Comment by themikesmith** [comment]
Hello, quoting the field seems to have resolved this error. FYI.

**Comment by poliquin** [comment]
@themikesmith, Do you have some addresses that can reliably produce this problem? I have the same issue, but I cannot make it happen consistently. I'd like to research what's causing this.

**Comment by themikesmith** [comment]
Hi Chris, unfortunately I don't have any such addresses. Please do let me
know if you make any headway!
Best
Mike

**Comment by fitnr** [comment]
This appears to have been an issue from the API side.
