### ISSUE TITLE
Urllib issues with python > 3.9

### ISSUE THREAD

**Issue by MrMalfunction** [fitnr/censusgeocode#29]
Getting error as follows
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/requests_toolbelt/_compat.py", line 48, in <module>
    from requests.packages.urllib3.contrib import appengine as gaecontrib
ImportError: cannot import name 'appengine' from 'requests.packages.urllib3.contrib' (/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/urllib3/contrib/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/runner/work/censusgeocode-test/censusgeocode-test/tests/__init__.py", line 10, in <module>
    from . import test_censusgeocode
  File "/home/runner/work/censusgeocode-test/censusgeocode-test/tests/test_censusgeocode.py", line 14, in <module>
    from censusgeocode import CensusGeocode
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/censusgeocode/__init__.py", line 10, in <module>
    from .censusgeocode import CensusGeocode
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/censusgeocode/censusgeocode.py", line 26, in <module>
    from requests_toolbelt.multipart.encoder import MultipartEncoder
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/requests_toolbelt/__init__.py", line 12, in <module>
    from .adapters import SSLAdapter, SourceAddressAdapter
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/requests_toolbelt/adapters/__init__.py", line 12, in <module>
    from .ssl import SSLAdapter
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/requests_toolbelt/adapters/ssl.py", line 16, in <module>
    from .._compat import poolmanager
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/requests_toolbelt/_compat.py", line 50, in <module>
    from urllib3.contrib import appengine as gaecontrib
ImportError: cannot import name 'appengine' from 'urllib3.contrib' (/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/urllib3/contrib/__init__.py)
```
After some research got to know requests-toolbelt==1.0.0 fixes it. Created a PR for it.

**Comment by lp804** [comment]
Was this resolved in v0.5.2? I am still coming across this error when importing the package.

**Comment by bmos** [comment]
Can we get a new release cut? It seems #28 isn't in the latest release.

**Comment by apancoast** [comment]
Had the same issue due to release installed with `pip install censusgeocode`. Reinstalled directly from git link, `pip install git+https://github.com/fitnr/censusgeocode.git` and issue resolved, in case that helps anyone.

**Comment by fitnr** [comment]
New release has been pushed, this should be fixed.
