### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by buckyswider** [fitnr/censusgeocode#4]
DISREGARD/DELETE!  Looks like I just didn't wait long enough, as this appears to have been a server-side issue.  It's working now with no changes to my code or local environment.  Thanks!  

Hi! I'm not fluent enough to recognize if this is a code error or a provider error- maybe they forgot to renew their certs??  I've had a piece of code that's been running very well for about 7 months now (aside from the occasional issue with the server being down, and documented in the other issue) but today started getting a new error.  I retried after 8 hours and the error persists, so it seems to be more than an intermittent outage this time.  (Also, my lack of fluency leads to a 'syntax error' when I try using the examples via command line, but that is probably just something I'm doing).  Here' the output.  Thanks!
````
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "C:\Python35\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 352, in _make_request
    self._validate_conn(conn)
  File "C:\Python35\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 831, in _validate_conn
    conn.connect()
  File "C:\Python35\lib\site-packages\requests\packages\urllib3\connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "C:\Python35\lib\site-packages\requests\packages\urllib3\util\ssl_.py", line 308, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Python35\lib\ssl.py", line 377, in wrap_socket
    _context=self)
  File "C:\Python35\lib\ssl.py", line 752, in __init__
    self.do_handshake()
  File "C:\Python35\lib\ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Python35\lib\ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)
````

**Comment by fitnr** [comment]
A new commit updates the requirements to include the required security libraries to avoid this error.

**Comment by flooie** [comment]
I'm receiving the same error. with current code
